name: publish
on:
  push:
    tags:
      - "v*.*.*"   # ex: v1.0.1
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write   # OIDC obligatoire pour Trusted Publisher

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist & wheel
        run: python -m build

      # Publie sur PyPI avec Trusted Publisher (pas de token à configurer)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
